# Generated by Django 4.2.6 on 2024-03-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_laptop_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
