"use client";

import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import useSearching from "@/hooks/useSearching";

const vazir = Vazirmatn({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isSearching, onCloseSearch } = useSearching();
  return (
    <html lang="en" dir="rtl">
      <body className={`${vazir.className} dark:bg-darker-user`}>
        <Navbar />
        <div className={`${isSearching ? "absolute lg:bg-blackOverlay" : ""}`}>
          <div
            className={`h-screen flex justify-center items-center  ${
              isSearching ? "z-40" : ""
            } `}
            onClick={onCloseSearch}
          >
            <div className="-z-10">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
