# Generated by Django 5.0.6 on 2024-06-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_id', models.CharField(max_length=200)),
                ('product_type', models.CharField(default='laptop', max_length=100)),
                ('product_id', models.BigIntegerField()),
            ],
        ),
    ]
