# Generated by Django 5.0.6 on 2024-06-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='product_type',
        ),
    ]
