version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - shopify_network
      - redis_network
    depends_on:
      - shopify_pg
      - redis
    links:
      - redis

  shopify_pg:
    image: postgres
    container_name: shopify_pg
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - shopify_data:/var/lib/postgresql/data/
    networks:
      - shopify_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - shopify_network
  nginx:
    build: ./webserver/.
    ports:
      - "81:80"
    depends_on:
      - web
    networks:
      - shopify_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - dev.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - mongo-data:/data/db
    networks:
      - shopify_network


volumes:
  shopify_data:
    driver: local
  mongo-data:
    driver: local

networks:
  shopify_network:
  redis_network:
