version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: python manage.py runserver 0.0.0.0:3000
    networks:
      - shopify_network
      - redis_network
    depends_on:
      - shopify_pg
      - redis
    links:
      - redis

  shopify_pg:
    image: postgres
    container_name: shopify_pg
    env_file:
      - env/.env
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - shopify_data:/var/lib/postgresql/data/
    networks:
      - shopify_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - shopify_network
  nginx:
    build: ./webserver/.
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - shopify_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  shopify_data:
    driver: local
  mongo-data:
    driver: local

networks:
  shopify_network:
  redis_network:
